# global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'fruit-demo'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker.for.mac.localhost:8082']
        labels:
          application: fruit-demo
  - job_name: 'spring-boot-demo'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['docker.for.mac.localhost:8081']
        labels:
          application: spring-boot-demo
